configs:
    - configs/datasets/glossysynthetic/glossysynthetic.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        data_root: /mnt/data/easyvolcap/GlossySynthetic/potion/train
        view_sample: [0, null, 1]

val_dataloader_cfg:
    dataset_cfg:
        data_root: /mnt/data/easyvolcap/GlossySynthetic/potion/test
        view_sample: [0, null, 1]
model_cfg:
    sampler_cfg:
        preload_gs: /mnt/data/easyvolcap/GlossySynthetic/potion/points/pcds/points3d.ply
        spatial_scale: 5.202147674560547
        # Environment Gaussian
        env_preload_gs: /mnt/data/easyvolcap/GlossySynthetic/potion/points/envs/points3d.ply
        env_bounds: [[-50.0, -50.0, -50.0], [50.0, 50.0, 50.0]]
